### PR TITLE
add support for phpunit 11

### PR DESCRIPTION
**Pull request by wickedOne**
allow installation of phpunit 11
removed conflict section as well as it won't install phpunit <9.6 anyway?

### CODE REVIEW

**Comment by mbabker** [comment]
> removed conflict section as well as it won't install phpunit <9.6 anyway?

The `conflict` section would be what blocks installing this package alongside unsupported PHPUnit versions in downstream apps/packages.  Realistically, I'd say the `phpunit/phpunit` dependency should be in the `require` section instead of `require-dev` since this is a PHPUnit extension of sorts, but for packages where you have an optional dependency not in the `require` section of the Composer manifest, using the `conflict` section creates a functionally equivalent result.

**Comment by Spomky** [comment]
Hi,

@matthiasnoback do you think this PR is ready and could be merged/tagged?

**Comment by wickedOne** [comment]
@Spomky matthiaas is no longer involved in these repos (or so i learned :-) )

ping @Nyholm

**Review by Nyholm — APPROVED** [review]
@mbabker If you are happy, feel free to merge.

**Comment by mbabker** [comment]
> @mbabker If you are happy, feel free to merge.

I would, but I don't have merge rights here.  I'm just one of those drive-by contributor types 😅

**Comment by Nyholm** [comment]
Oh. Sorry =)

**Comment by Spomky** [comment]
Many thanks @Nyholm 👍🏼
Works fine when using the master branch. Waiting for it to be tagged.
Regards.

**Pull request merged**
