### PR TITLE
feat: Symfony 7 support

### PR DESCRIPTION
**Pull request by kbond**
Adjusted the CI test matrix to add PHP 8.3 and only supported Symfony versions.

### CODE REVIEW

**Review by loic425 — APPROVED** [review]

**Comment by loic425** [comment]
@kbond Could we hope you merge it soon?
I'd like to start working on Symfony 7 support for Sylius packages and I need this support too.

**Comment by kbond** [comment]
Friendly ping @stloyd, @xabbuh, @Nyholm. This PR and https://github.com/SymfonyTest/SymfonyDependencyInjectionTest/pull/149 are blocking a bunch of bundles from being upgraded to support Symfony 7.

**Comment by loic425** [comment]
Another small and friendly ping to @stloyd, @xabbuh, @Nyholm.
RC1 is released and we all have a lot of work to do for Symfony 7 support :)
Thx a lot for all your work.

**Review by Nyholm — APPROVED** [review]
Thank you

**Comment by Nyholm** [comment]
Can someone verify this on their project before we do a release?

**Comment by loic425** [comment]
> Can someone verify this on their project before we do a release?

Hum I think we all use it via matthiasnoback/symfony-dependency-injection-test.
So I think we need this one to test it => https://github.com/SymfonyTest/SymfonyDependencyInjectionTest/pull/149

**Comment by Nyholm** [comment]
Let's sneak this out then so CI pass on https://github.com/SymfonyTest/SymfonyDependencyInjectionTest/pull/149

**Comment by Nyholm** [comment]
A bunch more PRs have been merged on https://github.com/SymfonyTest/SymfonyDependencyInjectionTest

We've dropped sf 4.4 and php 7. 

Please test it out.

**Pull request merged**
