### PR TITLE
Fix requirements in composer.json

### PR DESCRIPTION
**Pull request by delboy1978uk**
This fixes https://github.com/SymfonyTest/SymfonyConfigTest/issues/47

### CODE REVIEW

**Comment by delboy1978uk** [comment]
awesome, thanks. great lib btw, I'm using it right now!  😃

**Comment by xabbuh** [comment]
FYI, this has been done multiple times in the past but has always been rejected afterwards (see for example #33) to not mess things up for people who do not (want to) install PHPUnit as part of their project dependencies (for example, they have a global PHPUnit installation or use the Symfony PHPUnit bridge).

**Comment by delboy1978uk** [comment]
@xabbuh, I add this lib to MY require-dev, so that makes no sense.

**Comment by xabbuh** [comment]
But it doesn't mean that you do not want to use a globally installed PHPUnit version or the Symfony PHPUnit bridge.

**Comment by delboy1978uk** [comment]
It installs pre-broken on some systems if you don't. That's why I raised the issue. Also, isn't it telling that people keep asking for this?

**Comment by emodric** [comment]
My PR with this was also rejected before https://github.com/SymfonyTest/SymfonyConfigTest/pull/37 :)

@xabbuh What exactly prevents usage of globally installed PHPUnit PHAR file or simple PHPUnit from the bridge if PHPUnit is added to project dependencies?

**Comment by xabbuh** [comment]
You do not have the precise control over which classes are actually loaded which can lead to conflicts when your global PHPUnit version is different from the one being installed as a dependency.

**Comment by Nyholm** [comment]
Could we use ‘conflicts’ in composer.json instead?

**Comment by delboy1978uk** [comment]
Have a look at the comments from Jordi of Composer and Sebastian of PHPUnit in this ticket. The recommended way is to require it in to the project and not use the global one. However a solution for that is also on its way. 
https://github.com/sebastianbergmann/phpunit/issues/2014

**Comment by Nyholm** [comment]
Fixed by #50

**Pull request closed without merging**
