### PR TITLE
Add return typehints to toString methods for compatibility with PHPUnit 7.0

### PR DESCRIPTION
**Pull request by emodric**
Contravariance makes it possible for this to be compatible with both PHPUnit 6 with no return type hints.

### CODE REVIEW

**Comment by Nyholm** [comment]
Isnt this considered as a BC break?

**Comment by emodric** [comment]
@Nyholm In what sense? If someone extended these, or? In that case, it could be considered a BC break I guess.

**Comment by Nyholm** [comment]
Exactly. 

I mean. I do like the change and I think we should do it. But how should we release the next version?

**Comment by emodric** [comment]
Is there a reason not to release 4.0? Maybe it would be worthwile to introduce scalar typehints all over for 4.0, too.

**Comment by Nyholm** [comment]
See https://github.com/SymfonyTest/SymfonyConfigTest/issues/46

**Comment by emodric** [comment]
Thank you for review @Nyholm ! :)

**Pull request merged**
